apiVersion: v1
kind: Service
metadata:
  name: cortex-backend
  labels:
    app: cortex-backend
spec:
  selector:
    app: cortex-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
